<?php

return array(
	'id',
  '_updated',

  'basic.city',
  'basic.commNodeGeoArea',
  'basic.customReferenceId',
  'basic.displayAddress',
  'basic.forSale',
  'basic.gla',
  'basic.marketingBlurb',
  'basic.name',
  'basic.ownerName',
  'basic.ownerType',
  'basic.primaryCategory',
  'basic.propertyFundDomainKey',
  'basic.propertyGrade',
  'basic.propertyGradeDate',
  'basic.province',
  'basic.provinceGeoArea',
  'basic.strategicAction',
  'basic.strategicImportance',
  'basic.subCategory',
  'basic.suburb',
  'basic.value',
  'basic.valueM2',

  'equity.debtBalance',
  'equity.debtBalanceDate',
  'equity.debtBalanceLTV',
  'equity.debtFacility',
  'equity.debtFacilityLTV',
  'equity.debtFactilityDate',
  'equity.equityVsDebtBalance',
  'equity.equityVsDebtFacility',
  'equity.paidForDate',
  'equity.paidForValue',
  'equity.valueMovement',
  'equity.valueYoYMovement',

  'geo.lat',
  'geo.lon',

  'images._id',
  'images.contentDomainKey',
  'images.contentType',
  'images.length',
  'images.name',

  'ownership.type',
  'sales.askingPrice',
  'sales.purchasePrice',
  'sales.valueM2',
  'sales.yield',

  'vacancy.calculatedParkingRatio',
  'vacancy.currentVacantArea',
  'vacancy.signoffDate',
  'vacancy.totalUnitArea',
  'vacancy.unitSignoffDate',
  'vacancy.useVacantParkingRatio',
  'vacancy.vacantParkingRatio',
  'vacancy.weightedAskingRental',
  
  'valuations._id',
  'valuations.date',
  'valuations.isActive',
  'valuations.source',
  'valuations.value',
  
  'yard.access',
  'yard.askingRental',
  'yard.description',
  'yard.divisible',
  'yard.extent',
  'yard.has',
  'yard.leasedSeparately',
  'yard.other',
  'yard.type'
);